---ANALISAR A DISTRIBUIÇÃO DE SALÁRIOS POR DEPARTAMENTO E CARGO---

SELECT
    d.DEPARTMENT_NAME AS departamento,
    j.JOB_TITLE AS cargo,
    COUNT(e.EMPLOYEE_ID) AS quantidade_funcionarios,
    MIN(j.MIN_SALARY) AS menor_salario,
    MAX(j.MAX_SALARY) AS maior_salario

FROM HR.EMPLOYEES e
LEFT JOIN HR.DEPARTMENTS d
    ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
LEFT JOIN HR.JOBS j
    ON e.JOB_ID = j.JOB_ID
GROUP BY
    d.DEPARTMENT_NAME,
    j.JOB_TITLE
ORDER BY
    d.DEPARTMENT_NAME,
    j.JOB_TITLE;