--- COLETANDO AS INFORMAÇÕES DAS TABELAS EMPLOYEES, DEPARTAMENTES, JOBS, LOCATIONS, COUNTRIES E REGIONS E APLICANDO UM FILTRO DE SALARIOS MAIOR QUE 1000 E MENOR QUE 3000---
WITH RESULTADO_FUNCIONARIOS AS (
    SELECT
        E.EMPLOYEE_ID     AS ID_EMPREGADO,
        E.FIRST_NAME
        || ' '
        || E.LAST_NAME    AS NOME_FUNCIONARIO,
        R.REGION_NAME     AS REGIAO,
        C.COUNTRY_NAME    AS PAIS,
        L.CITY            AS CIDADE,
        D.DEPARTMENT_NAME AS DEPARTAMENTO,
        J.JOB_TITLE       AS CARGO,
        E.SALARY          AS SALARIO
    FROM
        HR.EMPLOYEES   E
        LEFT JOIN HR.DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
        LEFT JOIN HR.JOBS        J ON E.JOB_ID = J.JOB_ID
        LEFT JOIN HR.LOCATIONS   L ON D.LOCATION_ID = L.LOCATION_ID
        LEFT JOIN HR.COUNTRIES   C ON L.COUNTRY_ID = C.COUNTRY_ID
        LEFT JOIN HR.REGIONS     R ON C.REGION_ID = R.REGION_ID
    WHERE
            E.SALARY > 1000
        AND E.SALARY < 3000
)
SELECT
    ID_EMPREGADO,
    NOME_FUNCIONARIO,
    REGIAO,
    PAIS,
    CIDADE,
    DEPARTAMENTO,
    CARGO,
    SALARIO,
    COUNT(ID_EMPREGADO)
    OVER(PARTITION BY REGIAO, PAIS, CIDADE, DEPARTAMENTO, CARGO) AS QUANTIDADE_FUNCIONARIOS
FROM
    RESULTADO_FUNCIONARIOS
ORDER BY
    REGIAO,
    PAIS,
    CIDADE,
    DEPARTAMENTO,
    CARGO,
    NOME_FUNCIONARIO;